
require 'routes/about.rb'
require 'routes/contact.rb'
require 'routes/games.rb'
require 'routes/genres.rb'
require 'routes/profile.rb'
require 'routes/recomms.rb'
require 'routes/login.rb'
require 'routes/updates.rb'
require 'routes/profile.rb'
