require_relative 'contact.rb'
require_relative 'games.rb'
require_relative 'genres.rb'
require_relative 'profile.rb'
require_relative 'recomms.rb'
require_relative 'login.rb'
require_relative 'updates.rb'
require_relative 'profile.rb'
